# Generated by Django 4.1.6 on 2023-02-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_small', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('completed_on', models.DateField(verbose_name='date completed')),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.range')),
            ],
        ),
        migrations.CreateModel(
            name='HikeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.hike')),
            ],
        ),
        migrations.AddField(
            model_name='hike',
            name='mountains',
            field=models.ManyToManyField(to='hike.mountain'),
        ),
        migrations.AddField(
            model_name='hike',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.range'),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('completed_on', models.DateField(verbose_name='date completed')),
                ('hikes', models.ManyToManyField(to='hike.hike')),
                ('mountains', models.ManyToManyField(to='hike.mountain')),
            ],
        ),
    ]
