# Generated by Django 4.1.6 on 2023-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='hikes',
            field=models.ManyToManyField(blank=True, to='hike.hike'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='mountains',
            field=models.ManyToManyField(blank=True, to='hike.mountain'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='mountains',
            field=models.ManyToManyField(blank=True, to='hike.mountain'),
        ),
    ]
