# Generated by Django 4.1.6 on 2023-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0002_alter_challenge_hikes_alter_challenge_mountains_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hike',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='gain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='hike',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='hike.condition'),
        ),
    ]
