# Generated by Django 4.1.6 on 2023-02-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0003_condition_hike_duration_hike_gain_hike_mileage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='description',
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hike',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
