# Generated by Django 4.1.6 on 2023-02-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0004_remove_condition_description_challenge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='completed_on',
            field=models.DateField(null=True, verbose_name='date completed'),
        ),
    ]
