# Generated by Django 4.1.6 on 2023-02-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0005_alter_hike_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='completed_on',
            field=models.DateField(null=True, verbose_name='date completed'),
        ),
        migrations.AlterField(
            model_name='hike',
            name='range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hike.range'),
        ),
    ]
