# Generated by Django 4.1.6 on 2023-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0007_alter_challenge_completed_on_alter_hike_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='name_small',
            field=models.CharField(default='adk46', max_length=5),
            preserve_default=False,
        ),
    ]
