# Generated by Django 4.1.6 on 2023-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0008_challenge_name_small'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountain',
            options={'ordering': ['range', 'name']},
        ),
        migrations.AlterField(
            model_name='hike',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
