# Generated by Django 4.1.6 on 2023-02-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0010_difficulty_hike_difficulty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Difficulty',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='hike',
            old_name='difficulty',
            new_name='grade',
        ),
    ]
