# Generated by Django 4.1.6 on 2023-02-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0011_rename_difficulty_grade_rename_difficulty_hike_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='alltrails',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
