# Generated by Django 4.1.6 on 2023-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0012_hike_alltrails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='name_small',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
