# Generated by Django 4.1.6 on 2023-03-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0015_rename_traillinks_traillink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='hikedetail',
            name='hike_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hike.hikepart'),
        ),
    ]
